Task2
SlivnyiArtem/JavaBookBot pull request #12
Opened 2024-05-24 12:24 UTC by lenurseytasanov

2024-05-24 12:25 UTC, lenurseytasanov commented
Я замержил, master в task 2 напрямую, чтобы подтянуть изменения из task1

2024-06-06 05:45 UTC, vpyzhyanov requested changes
Что-то я так и не нашёл теста, который тестирует отложенную отправку сообщений.

Есть замечания. Тем не менее времени уже нет, поэтому ставлю то, что есть.

**За Git: 3 балла**

**За ООП: 2 балла**

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/utils/QueueProvider.java
> +public class QueueProvider {
Это оверинжиниринг. Но давайте проблемы по порядку:

1. Я слишком долго искал конфигурацию, которая создаёт эту очередь. А оказалось, что её не существует и конфигурация создаёт бины, которые её используют. Это очень не очевидно. Но даже если делаете так, то убирайте аннотацию `@Component` с этих бинов (Bot, BookWorker и др.), т.к. мы их создаёте вручную. А правильно было создавать в конфигурации только очередь.
2. Класс QueueProvider просто создаёт две очереди, хотя их можно было сразу создать в конфигурации. То есть класс лишний.
3. И зачем вам вообще понадобились блокирующие очереди? Вы не доверяете телеграмму и поэтому дублируете его логику?
4. И зачем вам вообще понадобились блокирующие очереди **с приоритетом**? Когда можно просто сделать планировщик и слать сообщение в нужное время. Сами усложнили себе жизнь и другим разработчикам, которые будут поддерживать код.

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/utils/SendScheduledMessage.java
> +public class SendScheduledMessage extends BotApiMethodMessage {
1. декоратор должен называться `Decorator`
2. Добро пожаловать в тёмную сторону ООП. Декоратор вам не нужен, вы создаёте 2 класса, вместо одного. Абсолютно во всех местах создаётся и `SendMessage` и `SendScheduledMessage` одновременно. Создавайте сразу нужный класс. Лучше расширьте `SendMessage` добавив туда время.

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/client/GoogleBooksApiClient.java
>      private static class BookList {
**static запрещён!!!** Неужели настолько сложно выполнить требования проекта?

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/worker/SendMessageWorkerTest.java
> +        try (MockedStatic<OffsetDateTime> offsetDateTime = Mockito.mockStatic(OffsetDateTime.class)) {
что-то никак не получается у вас освоить mockito. Не надо мокать простые классы, которые легко создать.

`java.time.OffsetDateTime#of(java.time.LocalDate, java.time.LocalTime, java.time.ZoneOffset)` или другие методы `of`

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/config/ApplicationConfig.java
> +public class ApplicationConfig {
Конфигурация, которая является посредником между бинами. Посредники никому не нужны. Удалить этот класс вообще

Если нужна очередь, создавайте бин с этой очередью, хотя тут и очередь не нужна.

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/domain/Book.java
> +                logger.warn("can't parse description: {}", e.getMessage());
Пожалуйста, не надо так. Стек не стоит выкидывать на помойку. Он может вам сильно помочь при разборе ошибок.

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/handler/commands/SetNotifyTimeCommandHandler.java
> +        chatUserService.setNotificationTime(command.username(), scheduledTime);
не самое лучшее решение. Не надо усложнять себе жизнь. Мы же разбирали этот случай. Можно передать интерфейс бота и отправить через него сообщение в нужный момент. Это намного проще и более ООП'шно. А тут получается ответственность за отправку сообщения команда делегирует неизвестно кому. Хотя именно команда отвечает за отправку сообщения пользователю.

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/service/BookTrackingService.java
> +                .filter(book -> book.getPublishedDate() != null
Добро пожаловать на тёмную сторону ООП. лучше операцию фильтрации отдать репозиторию. Это именно его задача. Задача сервиса - делать высокоуровневую логику, а не фильтровать данные.

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/service/BookTrackingService.java
> +                .filter(book -> {
то же самое

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/worker/BookWorker.java
> +        return new SendScheduledMessage(
Этот декоратор не нужен

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/worker/DispatchUpdateWorker.java
> +            logger.error(e.getMessage());
запись об ошибке без стека - это всё равно, что карта с сокровищами, на которой нарисован лишь крестик и больше ничего.

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/worker/DispatchUpdateWorker.java
> +                        logger.error(e.getMessage());
то же самое

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/worker/SendMessageWorker.java
> +                bot.execute(sendMessage);
О_о вот это поворот. Если вы и так отправляете сообщение в нужное время, то зачем вам вообще очередь?? Опять нарушение ООП.

1. Управлять очередью должен **только один класс**!
2. Об этой очереди никто больше не должен знать (инкапсуляция), наверное класс `SendMessageWorker`. Соответственно вся работа по отправке должна происходить через него

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/worker/SendMessageWorker.java
> +                sendQueue.put(sendMessage);
Зачем тогда доставали сообщение, если его просто кладёте обратно. Лишние действия. Можно было использовать метод `peek()`

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/worker/SendMessageWorker.java
> +            logger.error(e.getMessage());
потерялся стек. И сообщение об ошибке не человекочитаемое

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/handler/SetNotifyTimeCommandHandlerTest.java
> +        assertTrue(setNotifyTimeCommandHandler.canHandle(update));
похоже лекцию по тестированию вы не усвоили. Тест не полный. Он вообще не тестирует команду `/set_time`. Просто повторён антипример из лекций. Нет проверки, что время сохранено именно то, которое пользователь задал.

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/service/BookTrackingServiceTest.java
> +        assertEquals(List.of(book1, book2), actual);
Лучше использовать `assertIterableEquals`

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/worker/BookWorkerTest.java
> +                    if (botApiMethodMessage instanceof SendMessage message) {
бессмысленная проверка. Вы в этом же методе определяете тип

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/worker/BookWorkerTest.java
> +                    } else if (botApiMethodMessage instanceof SendScheduledMessage scheduledMessage
не надо логику писать в тесте. Пишите тест. Дублировать логику не надо.

2024-06-06 05:45 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/worker/BookWorkerTest.java
> +        assertEquals(expected, actual);
похоже тест ничего не тестирует. Сам создал оба списка и в их создании тестируемый класс bookWorker никак не участвовал

2024-06-21 08:05 UTC, merged