Task1
SlivnyiArtem/JavaBookBot pull request #6
Opened 2024-05-13 17:27 UTC by lenurseytasanov

2024-05-15 20:12 UTC, vpyzhyanov commented
**Git:**

Обнаружен прямой коммит в ветку task1 (подозреваю, что их больше), это -1 балл.

В пулл реквестах творится что-то непонятное. Пулл реквесты просто закрываются и никуда не идут. По идее у вас есть уже 2 задачи, но в ветку task1 нет ни одного пулл реквеста, а должно быть как минимум 2. За это ещё -1 балл.

![image](https://github.com/SlivnyiArtem/JavaBookBot/assets/71599019/648292fa-a0b8-4884-a885-bee972c76189)

Пойдите и почитайте регламент, там написано как надо назвать ветки и как вести работу с пулл реквестами. Курс сдаст только тот, кто соблюдает регламент.

P.S. при удалении ветки закрывается пулл реквест. Что делать в этом случае: во первых ни в коем случае нельзя удалять ветку при активном пулл реквесте, во вторых его можно переоткрыть (не уверен что это можно сделать в GitHub)

**Итого:** 1 балл за Git

2024-05-15 21:16 UTC, vpyzhyanov requested changes
Много критичных проблем.

Тесты не смотрел. Посмотрю через 2,5 недели =D

2024-05-15 21:16 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/services/UserMessageProcessor.java
> +    // TODO fix dependency; fix search command bugs
надо исправить

2024-05-15 21:16 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/services/UserMessageProcessor.java
> +public class UserMessageProcessor {
тоже что-то не сервис не похоже

2024-05-15 21:16 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/services/UserMessageProcessor.java
> +            LOG.error("don't supported update received");
это точно ошибка? Может warn?

2024-05-15 21:16 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/services/handlers/callbacks/BookInfoService.java
> +public class BookInfoService implements CommandHandler {
100% не сервис

2024-05-15 21:16 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/services/handlers/callbacks/BookInfoService.java
> +            LOG.warn("book isbn not found in db", e);
Дублирование кода. Добро пожаловать на тёмную сторону ООП

2024-05-15 21:16 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/services/handlers/callbacks/RemoveBookService.java
> +            LOG.warn("book isbn not found in db", e);
везде дублируется одно и то же. Вот бы сервис пригодится сейчас. Жалко, что у вас нет ни одного настоящего, только названия есть.

2024-05-15 21:16 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/utils/dto/BookListApiDto.java
> +package ru.urfu.bot.utils.dto;
как DTO может относится к utils? мне не понятно. У DTO вполне конкретная цель и точно не утилитарная.

2024-05-15 21:16 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/bot/Bot.java
> +    public Bot(
лучше всегда явно писать `@Inject` или `@Autowired`

2024-05-15 21:16 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/bot/Bot.java
> +                throw new RuntimeException(e);
1. прошу всегда писать человекочитаемые сообщения об ошибках, а не просто оборачивать исключения
2. А вы точно хотите уронить всё приложение целиком просто потому, что одна команда не смогла обработаться?

2024-05-17 19:35 UTC, vpyzhyanov requested changes
по тестам тоже есть замечания

2024-05-17 19:35 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/MessageProcessorTest.java
> +    void messageUpdateTest(){
Нет JavaDoc

2024-05-17 19:35 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/MessageProcessorTest.java
> +    private Map<CommandType, CommandHandler> commandMap;
![image](https://github.com/SlivnyiArtem/JavaBookBot/assets/71599019/197d988c-033d-4876-8580-56bfd973e4b9)

2024-05-17 19:35 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/MessageProcessorTest.java
> +        when(commandMap.get(eq(CommandType.START))).thenReturn(mock(CommandHandler.class));
лишнее

2024-05-17 19:35 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/MessageProcessorTest.java
> +        when(commandMap.get(eq(CommandType.UNKNOWN))).thenReturn(commandHandler);
тест ничего не проверяет. Вся суть проверки `UserMessageProcessor` в том, что он вызывает правильную зарегистрированную команду. А тут проверяется только то, что вызывается какая-то "неизвестная" команда.

2024-05-17 19:35 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/MessageProcessorTest.java
> +        when(commandMap.get(eq(CommandType.UNKNOWN))).thenReturn(callbackHandler);
то же самое

2024-05-17 19:35 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/ParserTest.java
> +    Parser parser;
нарушения инкапсуляции

2024-05-17 19:35 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/ParserTest.java
> +    private static Stream<Arguments> provideMessageUpdates() {
static запрещён

2024-05-17 19:35 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/ParserTest.java
> +    void messageUpdateTest(String text, Command expected) {
JavaDoc. Во всех остальных классах тоже

2024-05-17 19:35 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/CommandsTest/AddBookServiceTest.java
> +    private User user;
![image](https://github.com/SlivnyiArtem/JavaBookBot/assets/71599019/bcd9b014-df04-4afa-9247-5f8571795948)

2024-05-17 19:35 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/CommandsTest/AddBookServiceTest.java
> +    private Book book;
аналогично

2024-05-17 19:35 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/CommandsTest/BookInfoServiceTest.java
> +                .chatId(chatId).text("Книга не найденна в коллекции пользователя")
Орфографическая ошибка

2024-05-17 19:35 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/services/handlers/commands/StartBotService.java
> +    @Transactional
зря про транзакции не послушали. Не делали бы таких ошибок

2024-05-20 12:18 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/services/handlers/callbacks/AddBookService.java
> +                    .orElseThrow(BookNotFoundException::new);
исправил

2024-05-20 12:18 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/services/handlers/callbacks/AddBookService.java
> +            User user = userRepository.findByUserName(username).orElseThrow(UserNotFoundException::new);
исправил

2024-05-20 12:19 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/services/handlers/callbacks/AddBookService.java
> +            LOG.error("book isbn not found in db and source", e);
исправил

2024-05-20 12:29 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/services/handlers/callbacks/AddBookService.java
> +    private static final Logger LOG = LoggerFactory.getLogger(AddBookService.class);
нет, случайно. Мне казалось, что, если static приватный, то вреда нет. Тем более логгер относится скорее к классу, чем к экземпляру. В любом случае, исправлено.

2024-05-20 12:29 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/services/handlers/callbacks/AddBookService.java
> + * Сохраняет книгу по isbn коду в коллекцию конретного пользователя.
исправил

2024-05-20 12:32 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/services/handlers/callbacks/AddBookService.java
> +package ru.urfu.bot.services.handlers.callbacks;
постарался исправить обработчики, вынеся работу над сущностями в другой класс.

2024-05-20 12:39 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/services/handlers/callbacks/AddBookService.java
> +public class AddBookService implements CommandHandler {
поменял. Я же правильно понимаю, что сервисами обычно называют классы для работы с доменными объектами и базой данных? Тогда почему, в данной реализации, обработчики не являются сервисами?

2024-05-20 12:47 UTC, lenurseytasanov commented on pom.xml
> +    <module>bot</module>
изначально планировался многомодульный проект. Пока не менял, может потом разделю проект на модули.

2024-05-20 12:48 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/config/README.md
заменил всё на package-info

2024-05-20 12:48 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/config/ApplicationConfig.java
> +        return new TelegramBotsApi(DefaultBotSession.class);
исправил

2024-05-20 12:49 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/config/ApplicationConfig.java
> +                CommandType.START, context.getBean(StartBotService.class),
поменял Map на List и убрал бин

2024-05-20 12:54 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/config/ApplicationConfig.java
> +        return new ModelMapper();
потому что он может быть нужен в разных классах. Таким образом, можно настроить его в одном месте, и не создавать и конфигурировать каждый раз. Правда здесь он в стандартной конфигурации. Убрал его вообще.

2024-05-20 12:54 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/controllers/GoogleBooksApiClient.java
> +public class GoogleBooksApiClient {
исправил

2024-05-20 12:59 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/utils/dto/BookApiDto.java
> +    private Long isbn13;
просто в json'е из Google Books API есть значения ISBN_10 и ISBN_13, где 10 и 13 это колличество знаков числа, а мы берем ISBN_13. Исправил

2024-05-20 13:16 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/utils/dto/BookApiDto.java
> +public class BookApiDto {
не совсем полял, почему обращение к API не является клиент-серверными взаимодействием. Ну а DTO нужны для десериализации JSON. Можно, конечно, этот фунционал реализовать прямо в `Book`, но разве хорошо, когда один класс представляет и доменный объект, и схему таблицы БД, и DTO?

2024-05-20 13:21 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/db/entities/Book.java
> +    private Long isbn13;
убрал

2024-05-20 13:21 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/db/exceptions/BookNotFoundException.java
> +public class BookNotFoundException extends NoSuchElementException { }
исправил

2024-05-20 13:21 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/db/exceptions/UserNotFoundException.java
> +public class UserNotFoundException extends NoSuchElementException { }
исправил

2024-05-20 13:21 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/db/repositories/JpaBookRepository.java
> +public interface JpaBookRepository extends JpaRepository<Book, Long> {
исправил

2024-05-20 13:22 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/services/Parser.java
> +public class Parser {
исправил

2024-05-20 13:23 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/services/Parser.java
> +    public Command parseCommand(Update update) {
исправил

2024-05-20 13:24 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/services/UserMessageProcessor.java
> +    // TODO fix dependency; fix search command bugs
убрал коментарий

2024-05-20 13:24 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/services/UserMessageProcessor.java
> +public class UserMessageProcessor {
изменил реализацию. Надеюсь так стало лучше.

2024-05-20 13:25 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/services/UserMessageProcessor.java
> +            LOG.error("don't supported update received");
согласен, исправлено

2024-05-20 13:25 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/services/handlers/callbacks/BookInfoService.java
> +public class BookInfoService implements CommandHandler {
исправил

2024-05-20 13:27 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/services/handlers/callbacks/BookInfoService.java
> +            LOG.warn("book isbn not found in db", e);
вынес обработку исключений в абстрактный класс, используя паттерн Шаблонный метод

2024-05-20 13:27 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/services/handlers/callbacks/RemoveBookService.java
> +            LOG.warn("book isbn not found in db", e);
исправил, наверное

2024-05-20 13:27 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/utils/dto/BookListApiDto.java
> +package ru.urfu.bot.utils.dto;
исправил

2024-05-20 13:28 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/bot/Bot.java
> +    public Bot(
исправил

2024-05-20 13:28 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/bot/Bot.java
> +                throw new RuntimeException(e);
нет, не хочу. Заменил на вывод в логгер.

2024-05-20 13:29 UTC, lenurseytasanov commented on bot/src/test/java/ru/urfu/bot/MessageProcessorTest.java
> +    void messageUpdateTest(){
исправил

2024-05-20 13:29 UTC, lenurseytasanov commented on bot/src/test/java/ru/urfu/bot/MessageProcessorTest.java
> +    private Map<CommandType, CommandHandler> commandMap;
исправил

2024-05-20 13:29 UTC, lenurseytasanov commented on bot/src/test/java/ru/urfu/bot/MessageProcessorTest.java
> +        when(commandMap.get(eq(CommandType.START))).thenReturn(mock(CommandHandler.class));
исправил

2024-05-20 13:29 UTC, lenurseytasanov commented on bot/src/test/java/ru/urfu/bot/MessageProcessorTest.java
> +        when(commandMap.get(eq(CommandType.UNKNOWN))).thenReturn(commandHandler);
поменял этот тест

2024-05-20 13:30 UTC, lenurseytasanov commented on bot/src/test/java/ru/urfu/bot/MessageProcessorTest.java
> +        when(commandMap.get(eq(CommandType.UNKNOWN))).thenReturn(callbackHandler);
исправил

2024-05-20 13:39 UTC, lenurseytasanov commented on bot/src/test/java/ru/urfu/bot/ParserTest.java
> +    Parser parser;
не исправил. Я так понимаю, у класса `Update` нарушается закон Деметры. Поэтому можно напрямую мокать связанные с `Update` объекты типа `Messege`, `User` и т.д. Но тоже самое делает `@Mock(answer = Answers.RETURNS_DEEP_STUBS)`.  Либо можно создавать все эти классы мануально. Но там конструкторы с десятками параметров. Не подскажите, как правильно получить экземпляр `Update` в данном случае?

2024-05-20 13:41 UTC, lenurseytasanov commented on bot/src/test/java/ru/urfu/bot/ParserTest.java
> +    private static Stream<Arguments> provideMessageUpdates() {
исправил

2024-05-20 13:41 UTC, lenurseytasanov commented on bot/src/test/java/ru/urfu/bot/ParserTest.java
> +    void messageUpdateTest(String text, Command expected) {
исправил

2024-05-20 13:41 UTC, lenurseytasanov commented on bot/src/test/java/ru/urfu/bot/CommandsTest/AddBookServiceTest.java
> +    private User user;
исправил

2024-05-20 13:41 UTC, lenurseytasanov commented on bot/src/test/java/ru/urfu/bot/CommandsTest/AddBookServiceTest.java
> +    private Book book;
исправил

2024-05-20 13:41 UTC, lenurseytasanov commented on bot/src/test/java/ru/urfu/bot/CommandsTest/BookInfoServiceTest.java
> +                .chatId(chatId).text("Книга не найденна в коллекции пользователя")
исправил

2024-05-20 13:42 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/services/handlers/commands/StartBotService.java
> +    @Transactional
Извините, что не присутствовал. Можете дать намек, в чем ошибка?

2024-05-20 20:55 UTC, vpyzhyanov commented
![image](https://github.com/SlivnyiArtem/JavaBookBot/assets/71599019/5bb6f2f7-2cb1-4d72-9b5e-0abfdcebdfcb)

Что-то я смотрю снижение баллов вас ничему не учит. Мне снять остальные баллы? Или только один Ленур работает и ему одному баллы ставить?

2024-05-20 21:01 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/services/handlers/callbacks/AddBookService.java
> +    private static final Logger LOG = LoggerFactory.getLogger(AddBookService.class);
В обычном проекте static для логгера - совершенно нормальное явление. Но у нас есть чёткие требования, мы учимся делать проекты без static. Тем более в этом случае легко без него обойтись.

2024-05-20 21:20 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/bot/Bot.java
> +            logger.error(e.getMessage());
нет смысла продолжать выполнение программы, если бота не удалось запустить

2024-05-20 21:20 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/bot/BotUpdateDispatcher.java
> +        this.updateHandlers = updateHandlers;
Лучше из этого списка сформировать Map и доставать обработчики более эффективно

2024-05-20 21:20 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/bot/BotUpdateDispatcher.java
> +        } catch (NullPointerException ignored) { }
В смысле `NullPointerException`?! Зачем? Срочно убрать!

Либо надо написать что-то осмысленное, либо наиболее общий `Exception`

2024-05-20 21:20 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/handler/UpdateHandler.java
> +    record Command(@NotEmpty String[] args, @NotBlank String username, @NotNull Long chatId) { }
Нет ни одной причины почему этот класс должен быть внутри этого интерфейса. Они вообще никак не связаны друг с другом!

2024-05-20 21:20 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/bot/BotUpdateDispatcher.java
> +        logger.warn("don't supported update received: %s".formatted(update.toString()));
форматирование съехало

2024-05-20 21:20 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/handler/callbacks/CallbackUpdateHandler.java
> +            } catch (NullPointerException | ConstraintViolationException e) {
1. `NullPointerException` - это внутреннее исключение, которое в нормальной жизни не должно никогда происходить. Убрать!
2. Ни одни метод не декларирует `ConstraintViolationException`. Либо надо декларировать в каком случае он возникнет, либо точно так же убрать, как и NPE 
3. Похоже на обработку какой-то внутренней логики, которая вынесена куда-то наружу и непонятно зачем. Похоже на коллективную безответственность

2024-05-20 21:20 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/services/handlers/callbacks/AddBookService.java
> +public class AddBookService implements CommandHandler {
Сервис - это класс более высокого уровня, который управляет класса уровня поменьше. А ещё у каждого сервиса есть своя уникальная задача.

> Я же правильно понимаю, что сервисами обычно называют классы для работы с доменными объектами и базой данных?

Как правило да. Но сервис может быть ещё более высокоуровневым и управлять другими сервисами меньшего уровня. Но самые высокоуровневые классы сервисами обычно никто не называет, т.к. слово service означает "служить". Самые высокоуровневые - это обработчики действий пользователя.

2024-05-20 21:23 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/config/ApplicationConfig.java
> +                CommandType.START, context.getBean(StartBotService.class),
А вот Map можно было не убирать, можно было сформировать этот Map в конструкторе. В идеале использовать полиморфизм, чтобы сформировать ключи. Так получится реализовать принцип открытой закрытости SOLID.

2024-05-20 21:30 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/controllers/GoogleBooksApiClient.java
> +        return Optional.of(modelMapper.map(bookApiDto, Book.class));
Немного описал в предыдущем комментарии. Ну и упражнение для вас: попробуйте описать в чём необходимость использования DTO и modelMapper в вашем случае.

2024-05-20 21:42 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/ParserTest.java
> +    Parser parser;
Как будь-то ответ написан на какое-то другое замечание. Замечания про Update не было.

Вы точно видите к какой строчке написано замечание? Вы точно прочитали, что речь про инкапсуляцию, а не про что-то другое?

2024-05-20 21:45 UTC, vpyzhyanov commented on bot/src/main/java/ru/urfu/bot/services/handlers/commands/StartBotService.java
> +    @Transactional
Если транзакцию открывать на сервисе или, не дай Бог, на Repositiry (DAO), то это напрочь ломает всю транзакционность. Транзакция должна открываться сразу как только получено сообщение от пользователя. Все действия по обработке этого сообщения должны быть в **одной** транзакции.

2024-05-20 21:48 UTC, vpyzhyanov requested changes
Как исправите последние замечания, можете мёрджить

2024-05-20 21:50 UTC, vpyzhyanov commented on bot/src/test/java/ru/urfu/bot/ParserTest.java
> +    Parser parser;
Кстати,  закон Деметры - это как раз про ниспадающее программирование) Точнее ниспадающее программирование помогает упростить соблюдение этого закона)

2024-05-22 15:28 UTC, merged

2024-05-24 11:13 UTC, lenurseytasanov commented on bot/src/main/java/ru/urfu/bot/bot/BotUpdateDispatcher.java
> +        this.updateHandlers = updateHandlers;
проблема в том, что Update нельзя универсально спарсить и на его основе сформировать ключи. Каждый обработчик сам решает, как ему обрабатывать Update. Поэтому, на мой взгляд, здесь бы лучше подошла цепочка обязанностей.